//! Embedded HTTP server for **phone voice mode**.
//!
//! The box runs vault-chat 24/7. This tiny server lets a phone — over the
//! user's private Tailscale mesh — drive a *live* ElevenLabs voice session whose
//! brain (vault context + tools) stays on the box. The phone is just ears and
//! mouth; everything that touches the vault happens here.
//!
//! Security model (user-chosen): **Tailscale-only + a shared token**. Every
//! route except `/health` requires the token (header `X-Vault-Token` or
//! `?token=`). The token is generated by the desktop app and handed to the
//! phone out-of-band (shown in Settings / as a QR), never hardcoded.
//!
//! Tool execution is deliberately **scoped to safe, read-style operations**
//! (read/search the vault, read conversations, set schedules) — never Bash or
//! file writes — so a network endpoint can't become "run anything on my box."
//!
//! This file is Stage 1: the token-guarded server foundation + `/health`. The
//! `/voice` page, `/session` minting (relayed to the desktop app, which already
//! builds the EL signed URL + context), and the safe `/tool` dispatch are wired
//! on top of this in later stages. The server is **inert until the app starts
//! it** (the user opts in), so simply shipping this file changes nothing.

use std::sync::{Arc, Mutex, OnceLock};
use tiny_http::{Header, Method, Request, Response, Server};

struct Running {
    server: Arc<Server>,
    token: String,
    port: u16,
}

static SERVER: OnceLock<Mutex<Option<Running>>> = OnceLock::new();

fn slot() -> &'static Mutex<Option<Running>> {
    SERVER.get_or_init(|| Mutex::new(None))
}

/// Start the voice server on `port`, guarded by `token`. Idempotent: a start
/// with the same port+token while already running is a no-op; a different
/// config tears the old listener down first. Binds `0.0.0.0` so it's reachable
/// over the Tailscale interface — the token is the gate, and `/health` is the
/// only thing served without it. Returns the bound port.
pub fn start(port: u16, token: String) -> Result<u16, String> {
    let mut guard = slot().lock().unwrap_or_else(|e| e.into_inner());
    if let Some(r) = guard.as_ref() {
        if r.port == port && r.token == token {
            return Ok(r.port);
        }
        r.server.unblock();
    }
    let server = Server::http(("0.0.0.0", port)).map_err(|e| e.to_string())?;
    let server = Arc::new(server);
    let token_for_thread = token.clone();
    let server_for_thread = server.clone();
    std::thread::Builder::new()
        .name("voice-http".into())
        .spawn(move || {
            for req in server_for_thread.incoming_requests() {
                handle(req, &token_for_thread);
            }
        })
        .map_err(|e| e.to_string())?;
    *guard = Some(Running { server, token, port });
    Ok(port)
}

/// Stop the server (unblocks the accept loop so its thread exits). No-op if not
/// running.
pub fn stop() {
    let mut guard = slot().lock().unwrap_or_else(|e| e.into_inner());
    if let Some(r) = guard.take() {
        r.server.unblock();
    }
}

pub fn is_running() -> bool {
    slot().lock().unwrap_or_else(|e| e.into_inner()).is_some()
}

fn json(status: u16, body: &str) -> Response<std::io::Cursor<Vec<u8>>> {
    let mut r = Response::from_string(body.to_string()).with_status_code(status);
    if let Ok(h) = Header::from_bytes(&b"Content-Type"[..], &b"application/json"[..]) {
        r = r.with_header(h);
    }
    r
}

/// The token may arrive as the `X-Vault-Token` header or a `?token=` query param
/// (the latter so a phone can open a plain URL). Constant-ish comparison is fine
/// here — the token is high-entropy and the surface is a private mesh.
fn token_ok(req: &Request, token: &str) -> bool {
    for h in req.headers() {
        if h.field.equiv("X-Vault-Token") && h.value.as_str() == token {
            return true;
        }
    }
    if let Some(q) = req.url().split('?').nth(1) {
        for kv in q.split('&') {
            if let Some(v) = kv.strip_prefix("token=") {
                if v == token {
                    return true;
                }
            }
        }
    }
    false
}

fn handle(req: Request, token: &str) {
    let path = req.url().split('?').next().unwrap_or("/").to_string();
    let method = req.method().clone();

    // Health is unauthenticated and reveals nothing — used to confirm the phone
    // can reach the box at all.
    if path == "/health" {
        let _ = req.respond(json(200, "{\"ok\":true}"));
        return;
    }
    if !token_ok(&req, token) {
        let _ = req.respond(json(401, "{\"error\":\"unauthorized\"}"));
        return;
    }

    match (method, path.as_str()) {
        // Stage 2+: serve the phone voice page, mint an EL session with vault
        // context (relayed to the desktop app), and dispatch the safe tool set.
        (Method::Get, "/voice") | (Method::Post, "/session") | (Method::Post, "/tool") => {
            let _ = req.respond(json(501, "{\"error\":\"not implemented yet\"}"));
        }
        _ => {
            let _ = req.respond(json(404, "{\"error\":\"not found\"}"));
        }
    }
}
