import * as monaco from "monaco-editor";
import { loader } from "@monaco-editor/react";
import editorWorker from "monaco-editor/esm/vs/editor/editor.worker?worker";
import jsonWorker from "monaco-editor/esm/vs/language/json/json.worker?worker";
import cssWorker from "monaco-editor/esm/vs/language/css/css.worker?worker";
import htmlWorker from "monaco-editor/esm/vs/language/html/html.worker?worker";
import tsWorker from "monaco-editor/esm/vs/language/typescript/ts.worker?worker";

self.MonacoEnvironment = {
  getWorker(_: unknown, label: string) {
    if (label === "json") return new jsonWorker();
    if (label === "css" || label === "scss" || label === "less") return new cssWorker();
    if (label === "html" || label === "handlebars" || label === "razor") return new htmlWorker();
    if (label === "typescript" || label === "javascript") return new tsWorker();
    return new editorWorker();
  },
};

// Graphite: --background = hsl(0 0% 10%) = #1a1a1a
// Light:    --background = hsl(0 0% 98%) = #fafafa
// Syntax colors approximate highlight.js's github-dark palette so code
// looks consistent between the Monaco editor and the rehype-highlight
// view mode.
const graphiteRules = [
  { token: "comment", foreground: "8b949e", fontStyle: "italic" },
  { token: "keyword", foreground: "ff7b72" },
  { token: "keyword.flow", foreground: "ff7b72" },
  { token: "keyword.json", foreground: "79c0ff" },
  { token: "string", foreground: "a5d6ff" },
  { token: "string.escape", foreground: "79c0ff" },
  { token: "string.key.json", foreground: "79c0ff" },
  { token: "string.value.json", foreground: "a5d6ff" },
  { token: "number", foreground: "79c0ff" },
  { token: "regexp", foreground: "a5d6ff" },
  { token: "type", foreground: "ffa657" },
  { token: "type.identifier", foreground: "ffa657" },
  { token: "function", foreground: "d2a8ff" },
  { token: "identifier", foreground: "ebebeb" },
  { token: "variable", foreground: "ffa657" },
  { token: "variable.predefined", foreground: "79c0ff" },
  { token: "constant", foreground: "79c0ff" },
  { token: "tag", foreground: "7ee787" },
  { token: "attribute.name", foreground: "79c0ff" },
  { token: "attribute.value", foreground: "a5d6ff" },
  { token: "delimiter", foreground: "ebebeb" },
  { token: "operator", foreground: "ff7b72" },
  { token: "metatag", foreground: "7ee787" },
];

monaco.editor.defineTheme("vault-graphite", {
  base: "vs-dark",
  inherit: true,
  rules: graphiteRules,
  colors: {
    "editor.background": "#1a1a1a",
    "editor.foreground": "#ebebeb",
    "editor.lineHighlightBackground": "#242424",
    "editorLineNumber.foreground": "#4a4a4a",
    "editorLineNumber.activeForeground": "#a8acb2",
    "editorGutter.background": "#1a1a1a",
    "editor.selectionBackground": "#3a3a45",
    "editorCursor.foreground": "#ebebeb",
    "editorIndentGuide.background1": "#262626",
    "editorBracketMatch.background": "#3a3a45",
    "editorBracketMatch.border": "#5a5a65",
    "editorWidget.background": "#1a1a1a",
    "editorWidget.border": "#2a2a2a",
  },
});

monaco.editor.defineTheme("vault-light", {
  base: "vs",
  inherit: true,
  rules: [],
  colors: {
    "editor.background": "#fafafa",
    "editor.foreground": "#1f1f23",
    "editorGutter.background": "#fafafa",
    "editorLineNumber.foreground": "#b0b0b0",
    "editorLineNumber.activeForeground": "#606060",
    "editor.lineHighlightBackground": "#f0f0f0",
  },
});

loader.config({ monaco });

export const extToMonacoLang: Record<string, string> = {
  md: "markdown",
  markdown: "markdown",
  mdx: "mdx",
  py: "python",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  tsx: "typescript",
  json: "json",
  jsonl: "json",
  yaml: "yaml",
  yml: "yaml",
  toml: "ini",
  xml: "xml",
  rs: "rust",
  go: "go",
  java: "java",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hh: "cpp",
  hxx: "cpp",
  cs: "csharp",
  rb: "ruby",
  rbw: "ruby",
  php: "php",
  phtml: "php",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  psm1: "powershell",
  bat: "bat",
  cmd: "bat",
  css: "css",
  scss: "scss",
  sass: "scss",
  less: "less",
  html: "html",
  htm: "html",
  xhtml: "html",
  svg: "xml",
  tex: "plaintext",
  bib: "plaintext",
  sql: "sql",
  r: "r",
  rmd: "r",
  jl: "julia",
  lua: "lua",
  ini: "ini",
  cfg: "ini",
  env: "ini",
  dockerfile: "dockerfile",
  makefile: "plaintext",
  mk: "plaintext",
  txt: "plaintext",
  log: "plaintext",
  lark: "plaintext",

  // Extended — all of these are Monaco's built-in monarch packs.
  gql: "graphql",
  graphql: "graphql",
  graphqls: "graphql",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  edn: "clojure",
  dart: "dart",
  scala: "scala",
  sbt: "scala",
  sc: "scala",
  ex: "elixir",
  exs: "elixir",
  fs: "fsharp",
  fsi: "fsharp",
  fsx: "fsharp",
  pas: "pascal",
  pp: "pascal",
  pl: "perl",
  pm: "perl",
  vb: "vb",
  vbs: "vb",
  m: "objective-c",
  mm: "objective-c",
  proto: "proto",
  tf: "hcl",
  tfvars: "hcl",
  hcl: "hcl",
  coffee: "coffeescript",
  scheme: "scheme",
  scm: "scheme",
  ss: "scheme",
  rkt: "scheme",
  sol: "solidity",
  rst: "restructuredtext",
  apex: "apex",
  cls: "apex",
  trigger: "apex",
  bicep: "bicep",
  wgsl: "wgsl",
  abap: "abap",
  tcl: "tcl",
  twig: "twig",
  liquid: "liquid",
  pug: "pug",
  jade: "pug",
  handlebars: "handlebars",
  hbs: "handlebars",
  mustache: "handlebars",
  azcli: "azcli",
  redis: "redis",
  pgsql: "pgsql",
  mysql: "mysql",
};
